language: python
services: mongodb
python:
  - "2.6"
  - "2.7"
#  - "3.3"  # dont work, e.g. pip cheetah fails
  
# TODO: install YUI via pip, but this is not (?) needed for unit tests  

# command to install dependencies
install: 
  - export PYCURL_SSL_LIBRARY=openssl # one may try: openssl or gnutls
  - pip install --use-mirrors -r requirements_freezed.txt  # install dependencies
  #- pip install --use-mirrors   pylint flake8 # not used yet: coverage

  - git clone https://github.com/dmwm/DASMaps
  - cp -r DASMaps/nltk $HOME/nltk_data
  #- python -m nltk.downloader -e words stopwords wordnet

  # use default MongoDB port which is available in travis
  - sed -i -e 's/8230/27017/g'  etc/das.cfg

  # install
  - python setup.py install
  - source ./init_env.sh
  - das_js_validate DASMaps/js
  - das_js_import DASMaps/js
  
  # init datasets cache (used in unit tests)
  - MONGO_PORT=27017
  - mongo --port "${MONGO_PORT}" "dbs" --eval "db.dropDatabase();"
  - mongoimport --port "${MONGO_PORT}" --db "dbs" --collection "prod/global" --file test/dataset_noid.js

# command to run tests
script: 
  - source ./init_env.sh
  - touch /tmp/x509up_u$UID  # hack for tests requiring certificates
  - python setup.py test
  #- flake8 --max-line-length=100 --statistics --exit-zero src # like pep8 but better, could also add --show-source
  # - das_code_quality 9 false  || true  # run pylint with threshold 9

  
notifications:
  email: true
#      on_success: never
      on_failure: always
  
# speedup the build slightly
matrix:
  fast_finish: true
