# CMSSW API mapping to DAS
system : cmsswconfigs
format : JSON
---
urn : cmssw_configs
url : "http://localhost:8889/cmsswconfigs/express_config"
expire : 86400
params : {"release": "required", "query": "required"}
lookup : config
das_map : [
    {"das_key":"config", "rec_key":"config", "api_arg":""},
    {"das_key":"release", "rec_key":"release.name", "api_arg":"release"},
    {"das_key":"search", "rec_key":"search", "api_arg":"query"},
]
