# Tier0 monitoring API mapping to DAS
system : cmsswconfigs
format : JSON
---
urn : cmssw_configs
url : "http://localhost:8889/cmsswconfigs/express_config"
expire : 86400
params : {"release": "required", "query": "required"}
daskeys : [
        {"key":"config", "map":"config", "pattern":""},
        {"key":"release", "map":"release.name", "pattern":""},
        {"key":"search", "map":"search", "pattern":""},
]
das2api : [
        {"das_key":"search","api_param":"query", "pattern":""},
        {"das_key":"release.name","api_param":"release", "pattern":""},
]
